; core
extension=bcmath
extension=ctype
extension=curl
extension=dom
extension=exif
extension=fileinfo
extension=gd
extension=gmp
extension=iconv
extension=intl
extension=mbstring
zend_extension=opcache
extension=openssl
extension=pcntl
extension=phar
extension=posix
extension=session
extension=simplexml
extension=sodium
extension=sysvsem
extension=xml
extension=xmlreader
extension=xmlwriter
extension=zip

; database
extension=mysqlnd
extension=mysqli
extension=pdo
extension=pdo_mysql
extension=pdo_pgsql

; cache & preview
extension=apcu
extension=igbinary
extension=msgpack
extension=redis
extension=imagick

[PHP]
output_buffering = Off
memory_limit = 512M
upload_max_filesize = 4M
post_max_size = 16M

apc.enable_cli = 1
opcache.validate_timestamps = 0
opcache.jit = 1255
opcache.jit_buffer_size = 128M
