#!/bin/sh

mkdir -p /data/data
mkdir -p /data/apps
mkdir -p /data/config

if [ -f /data/config/config.php ]; then
	php8 occ upgrade
	php8 occ maintenance:update:htaccess
else
	cat <<'EOF' >config/config.php
<?php
$CONFIG = array (
  'datadirectory' => '/data/data',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/data/apps',
      'url' => '/apps-ext',
      'writable' => true,
    ),
    1 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
);
EOF
	touch /data/config/CAN_INSTALL
fi

# prepare htaccess
mkdir /tmp/nextcloud
sed -e '/RewriteRule.*remote.php.*\[.*R=.*\]/s,/remote.php,%{HTTP:X-Forwarded-Proto}://%{HTTP:X-Forwarded-Host}/remote.php,g' .htaccess > /tmp/nextcloud/htaccess

cd /

exec /usr/local/sbin/httpd
